version: '3'
networks:
  configuration:
  userNet:
services:
  discovery:
    image: openjdk:8u212-jre-stretch
    volumes:
      - ./docker_environment/discovery/:/app
    working_dir: /app
    command: java -jar eureka-service.jar
    ports:
      - 8761:8761
    networks:
      - configuration
  proxy:
    image: openjdk:8u212-jre-stretch
    volumes:
      - ./docker_environment/proxy/:/app
    working_dir: /app
    command: java -jar zuul-service.jar
    ports:
      - 8762:8762
    networks:
      - configuration
      - userNet
    depends_on:
      - discovery
  user-db:
    image: mongo
    networks:
      - userNet
  user-service:
    image: openjdk:8u212-jre-stretch
    volumes:
      - ./docker_environment/user_service/:/app
    working_dir: /app
    command: java -jar user-service.jar
    networks:
      - userNet
      - configuration
    depends_on:
      - user-db
      - proxy