version: '3'
networks:
  configuration:
services:
  discovery:
    image: openjdk:8u212-jre-stretch
    volumes:
      - ./docker_environment/discovery/:/app
    working_dir: /app
    command: java -jar eureka-service.jar
    ports:
      - 8761:8761
    networks:
      - configuration
  proxy:
    image: openjdk:8u212-jre-stretch
    volumes:
      - ./docker_environment/proxy/:/app
    working_dir: /app
    command: java -jar zuul-service.jar
    ports:
      - 8762:8762
    networks:
      - configuration
    depends_on:
      - discovery